# Generated by Django 5.1.1 on 2025-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для публикации', null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
